# Generated by Django 3.1.6 on 2021-02-13 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=100, verbose_name='Progress')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=100, verbose_name='Priority')),
                ('created', models.DateTimeField(blank=True, help_text='Date this ticket was first created', verbose_name='Created')),
                ('modified', models.DateTimeField(blank=True, help_text='Date this ticket was most recently changed.', verbose_name='Modified')),
                ('description', models.TextField(blank=True, help_text='The content of the customers query.', null=True, verbose_name='Description')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
