# Generated by Django 3.1.6 on 2021-02-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20210213_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('helpdesk_admin', 'Administrators of helpdesk'),)},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date this ticket was first created', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, help_text='Date this ticket was most recently changed.', verbose_name='Modified'),
        ),
    ]
