# Generated by Django 3.1.6 on 2021-02-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20210215_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='ticket',
            name='text',
            field=models.TextField(blank=True, help_text='The content of the customers query.', null=True, verbose_name='Description'),
        ),
    ]
