# Generated by Django 3.1.6 on 2021-02-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20210215_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(default=1, help_text='The content of the customers query.', max_length=250, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=models.TextField(blank=True, help_text='The content of the customers query.', null=True, verbose_name='Text'),
        ),
    ]
