# Generated by Django 3.1.6 on 2021-02-15 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0005_auto_20210215_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ManyToManyField(to='ticket.Ticket')),
            ],
        ),
    ]
