# Generated by Django 3.1.6 on 2021-02-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ccusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccusers',
            name='ticket',
            field=models.ManyToManyField(related_name='cc', to='ticket.Ticket'),
        ),
    ]
