# Generated by Django 3.1.6 on 2021-02-15 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20210215_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccusers',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cc_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ticket.ccusers'),
            preserve_default=False,
        ),
    ]
