# Generated by Django 3.1.6 on 2021-02-15 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0008_auto_20210215_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cc_user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cc',
            field=models.ManyToManyField(related_name='cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
