# Generated by Django 3.1.6 on 2021-02-19 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0009_auto_20210215_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cc',
            field=models.ManyToManyField(blank=True, null=True, related_name='cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CCUsers',
        ),
    ]
