# Generated by Django 3.1.6 on 2021-02-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20210219_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='created_by',
        ),
    ]
