# Generated by Django 3.1.6 on 2021-03-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ticket.ticket', verbose_name='Ticket'),
        ),
    ]
