# Generated by Django 3.1.6 on 2021-03-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20210303_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='comment',
            field=models.TextField(blank=True, default=1, verbose_name='Comment'),
            preserve_default=False,
        ),
    ]
