# Generated by Django 3.1.6 on 2021-03-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_auto_20210303_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
