# Generated by Django 3.1.6 on 2021-03-05 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0015_auto_20210303_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ('-date',), 'verbose_name': 'Follow-up', 'verbose_name_plural': 'Follow-ups'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cc',
            field=models.ManyToManyField(blank=True, related_name='cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
