# Generated by Django 3.1.6 on 2021-03-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20210305_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
